[parameters]

[[parameters.weight]]
name = "Only A"
a = 1.0
b = 0.0
c = 0.0
d = 0.0

[[parameters.weight]]
name = "Only B"
a = 0.0
b = 1.0
c = 0.0
d = 0.0

[[parameters.weight]]
name = "Only C"
a = 0.0
b = 0.0
c = 1.0
d = 0.0

[[parameters.weight]]
name = "All 1.0"
a = 1.0
b = 1.0
c = 1.0
d = 1.0

[[parameters.weight]]
name = "Postgres defaults"
a = 1.0
b = 0.4
c = 0.2
d = 0.1

[[parameters.weight]]
name = "Title and others"
a = 1.0
b = 0.4
c = 0.4
d = 0.4

[[parameters.weight]]
name = "Lyrics priority"
a = 0.4
b = 0.2
c = 1.0
d = 0.1

[[parameters.normalization]]
name = "No normalization"
mode = 0

[[parameters.normalization]]
name = "Logarithmic"
mode = 1

[[parameters.normalization]]
name = "Linear"
mode = 2

[[parameters.normalization]]
name = "Harmonic"
mode = 4

[[parameters.normalization]]
name = "Linear unique"
mode = 8

[[parameters.normalization]]
name = "Logarithmic unique"
mode = 16


[[queries]]
filename = "life"
uin = "Find all songs with 'life' in the title."
type = "songs"
text = "life"
relevant = [137, 498, 541, 600, 269, 546, 589, 623, 631, 739, 745]

[[queries]]
filename = "specific"
uin = "Find the specific song 'here comes the sun'."
type = "songs"
text = "here comes the sun"
relevant = [438]

[[queries]]
filename = "specific_thesaurus"
uin = "Find the specific song 'here comes the sun' using the genre thesaurus."
type = "songs"
text = "here and comes and sun"
relevant = [438]
filter = 12

[[queries]]
filename = "specific_typo"
uin = "Accidentaly make a typo while searching 'here comes the sun'."
type = "songs"
text = "here cmoes the snu"
relevant = [438]

[[queries]]
filename = "and"
uin = "Find all songs with 'sky' and 'blue' in the lyrics."
type = "songs"
text = "sky and blue"
relevant = [484, 114, 258, 324, 441, 472, 524, 528, 692]

[[queries]]
filename = "and_or"
uin = "Find all lyrics with 'pain' or 'love' about 'life'."
type = "songs"
text = "(pain or love) and life"
relevant = [154, 151, 194, 235, 282, 316, 326, 328, 333, 404, 416, 454, 458, 496, 594, 716, 719, 745, 780]

[[queries]]
filename = "and not"
uin = "Find all songs with a title related to girls who don't cry."
type = "songs"
text = "girl and -cry"
relevant = [
    154,
    292,
    351,
    195,
    308,
    366,
    549,
]

[[queries]]
filename = "album_as_query"
uin = "Find songs about 'Jet Set Radio'."
type = "songs"
text = "jet set radio"
relevant = [
    776,
    756,
    757,
    758,
    762,
    763,
    764,
    765,
    787,
    786,
    782,
    783,
    773,
    759,
    760,
    761,
    766,
    767,
    774,
    768,
    769,
    770,
    771,
    772,
    775,
    777,
    778,
    779,
    780,
    781,
    784,
    785,
    788,
    789,
]

[[queries]]
filename = "artist_name"
uin = "Find the profile page of The Beatles."
type = "people"
text = "the beatles"
relevant = [307]
